# A conda environment with all useful package for ctapipe developers
name: pyirf-dev

channels:
  - default
dependencies:
  - python=3.7
  - astropy
  - numpy
  - ipython
  - jupyter
  - matplotlib
  - pytest
  - scipy
  - setuptools
  # docs
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - pip
  - pip:
      - rinohtype
      - nbsphinx
      - gammapy~=0.8.0
      - sphinx_automodapi
