# A conda environment with all useful package for ctapipe developers
name: pyirf-dev

channels:
  - default
dependencies:
  - astropy
  - numpy
  - ipython
  - jupyter
  - matplotlib
  - pytest
  - scipy
  - setuptools
  - sphinx
  - sphinx_rtd_theme
  - pip
